
module.exports.catDescMap = {
	animalpens             : '$l10n_category_animalpens',
	animals                : '$l10n_category_animals',
	animalsVehicles        : '$l10n_category_animals',
	animalTransport        : '$l10n_category_animalTransport',
	augerWagons            : '$l10n_category_augerWagons',
	baleLoaders            : '$l10n_category_baleLoaders',
	balers                 : '$l10n_category_balers',
	bales                  : '$l10n_category_bales',
	baleWrappers           : '$l10n_category_baleWrappers',
	beeHives               : '$l10n_category_beeHives',
	beetHarvesting         : '$l10n_category_beetHarvesting',
	beetVehicles           : '$l10n_category_beetHarvesting',
	belts                  : '$l10n_category_belts',
	bigbagPallets          : '$l10n_category_bigbagPallets',
	bigbags                : '$l10n_category_bigbags',
	cars                   : '$l10n_category_cars',
	chainsaws              : '$l10n_category_chainsaws',
	containers             : '$l10n_category_containers',
	cornHeaders            : '$l10n_category_cornHeaders',
	cottonHarvesting       : '$l10n_category_cottonHarvesting',
	cottonVehicles         : '$l10n_category_cottonHarvesting',
	cultivators            : '$l10n_category_cultivators',
	cutters                : '$l10n_category_cutters',
	cutterTrailers         : '$l10n_category_cutterTrailers',
	decoration             : '$l10n_category_decoration',
	dieselTanks            : '$l10n_category_dieselTanks',
	discHarrows            : '$l10n_category_discHarrows',
	dollys                 : '$l10n_category_dollys',
	farmhouses             : '$l10n_category_farmhouses',
	fences                 : '$l10n_category_fences',
	fertilizerSpreaders    : '$l10n_category_fertilizerSpreaders',
	fillableTanks          : '$l10n_category_fillableTanks',
	floodLighting          : '$l10n_category_floodLighting',
	forageHarvesterCutters : '$l10n_category_forageHarvestersCutters',
	forageHarvesters       : '$l10n_category_forageHarvesters',
	forklifts              : '$l10n_category_forklifts',
	frontLoaders           : '$l10n_category_frontLoaders',
	frontLoaderTools       : '$l10n_category_frontLoaderTools',
	frontLoaderVehicles    : '$l10n_category_frontLoaders',
	gardenSheds            : '$l10n_category_gardenSheds',
	generators             : '$l10n_category_generators',
	grapeTools             : '$l10n_category_grapeVehicles',
	grapeVehicles          : '$l10n_category_grapeVehicles',
	grasslandCare          : '$l10n_category_grasslandCare',
	harvesters             : '$l10n_category_harvesters',
	leveler                : '$l10n_category_leveler',
	loaderWagons           : '$l10n_category_loaderWagons',
	lowloaders             : '$l10n_category_lowloaders',
	manureSpreaders        : '$l10n_category_manureSpreaders',
	misc                   : '$l10n_category_misc',
	miscVehicles           : '$l10n_category_misc',
	mowers                 : '$l10n_category_mowers',
	mowerVehicles          : '$l10n_category_mowers',
	mulchers               : '$l10n_category_mulchers',
	objectAnimal           : '$l10n_category_animals',
	objectMisc             : '$l10n_category_objectMisc',
	oliveVehicles          : '$l10n_category_oliveVehicles',
	pallets                : '$l10n_category_pallets',
	placeableMisc          : '$l10n_category_placeableMisc',
	planters               : '$l10n_category_planters',
	plows                  : '$l10n_category_plows',
	potatoHarvesting       : '$l10n_category_potatoHarvesting',
	potatoVehicles         : '$l10n_category_potatoHarvesting',
	powerHarrows           : '$l10n_category_powerHarrows',
	productionPoints       : '$l10n_category_productionPoints',
	rollers                : '$l10n_category_rollers',
	seeders                : '$l10n_category_sowingMachines',
	sellingPoints          : '$l10n_category_sellingPoints',
	sheds                  : '$l10n_category_sheds',
	silocompaction         : '$l10n_category_silocompaction',
	siloExtensions         : '$l10n_category_siloExtensions',
	silos                  : '$l10n_category_silos',
	skidSteerTools         : '$l10n_category_skidSteerTools',
	skidSteerVehicles      : '$l10n_category_skidSteers',
	slurryTanks            : '$l10n_category_slurryTanks',
	slurryVehicles         : '$l10n_category_slurryTanks',
	spaders                : '$l10n_category_spaders',
	sprayers               : '$l10n_category_sprayers',
	sprayerVehicles        : '$l10n_category_cropProtection',
	stonePickers           : '$l10n_category_stonePickers',
	storages               : '$l10n_category_storages',
	subsoilers             : '$l10n_category_subsoilers',
	sugarcaneHarvesting    : '$l10n_category_sugarCaneHarvesting',
	sugarcaneVehicles      : '$l10n_category_sugarCaneHarvesting',
	tedders                : '$l10n_category_tedders',
	teleLoaderTools        : '$l10n_category_teleLoaderTools',
	teleLoaderVehicles     : '$l10n_category_teleLoaders',
	tractorsL              : '$l10n_category_tractorsL',
	tractorsM              : '$l10n_category_tractorsM',
	tractorsS              : '$l10n_category_tractorsS',
	trailers               : '$l10n_category_trailers',
	trees                  : '$l10n_category_trees',
	trucks                 : '$l10n_category_trucks',
	waterTanks             : '$l10n_category_waterTanks',
	weeders                : '$l10n_category_weeders',
	weights                : '$l10n_category_weights',
	wheelLoaderTools       : '$l10n_category_wheelLoaderTools',
	wheelLoaderVehicles    : '$l10n_category_wheelLoaders',
	windrowers             : '$l10n_category_windrowers',
	winterEquipment        : '$l10n_category_winterEquipment',
	wood                   : '$l10n_category_wood',
	woodHarvesting         : '$l10n_category_woodHarvesting',
}

module.exports.fillCats = {
	augerwagon      : ['wheat', 'barley', 'oat', 'canola', 'soybean', 'sunflower', 'maize', 'fertilizer', 'seeds', 'sorghum'],
	bulk            : ['wheat', 'barley', 'oat', 'canola', 'sunflower', 'soybean', 'maize', 'potato', 'sugarbeet', 'sugarbeet_cut', 'manure', 'seeds', 'forage', 'forage_mixing', 'chaff', 'woodchips', 'silage', 'straw', 'grass_windrow', 'drygrass_windrow', 'sugarcane', 'fertilizer', 'pigfood', 'lime', 'snow', 'roadsalt', 'sorghum', 'olive', 'stone', 'mineral_feed'],
	combine         : ['wheat', 'barley', 'oat', 'canola', 'sunflower', 'soybean', 'maize', 'sorghum'],
	farmsilo        : ['wheat', 'barley', 'oat', 'canola', 'sunflower', 'soybean', 'maize', 'sorghum'],
	forageharvester : ['chaff', 'grass_windrow', 'woodchips'],
	foragewagon     : ['straw', 'grass_windrow', 'drygrass_windrow', 'chaff', 'silage', 'forage'],
	fork            : ['manure', 'silage', 'chaff', 'straw', 'grass_windrow', 'drygrass_windrow'],
	hayloft         : ['straw', 'drygrass_windrow'],
	liquid          : ['milk', 'water', 'diesel', 'def'],
	loadingvehicle  : ['heat', 'barley', 'oat', 'canola', 'sunflower', 'soybean', 'maize', 'seeds', 'forage', 'chaff', 'woodchips', 'silage', 'fertilizer', 'lime', 'sorghum'],
	manurespreader  : ['manure'],
	mixerwagon      : ['forage', 'forage_mixing', 'drygrass_windrow', 'silage', 'straw', 'mineral_feed'],
	piece           : ['wool', 'treesaplings', 'egg'],
	product         : ['flour', 'bread', 'cake', 'butter', 'cheese', 'fabric', 'sugar', 'clothes', 'cereal', 'sunflower_oil', 'canola_oil', 'olive_oil', 'raisins', 'grapejuice', 'chocolate', 'boards', 'furniture', 'strawberry', 'lettuce', 'tomato', 'egg'],
	product_bga     : ['ethane', 'electriccharge'],
	shovel          : ['wheat', 'barley', 'oat', 'canola', 'sunflower', 'soybean', 'maize', 'potato', 'sugarbeet', 'sugarbeet_cut', 'manure', 'seeds', 'forage', 'forage_mixing', 'chaff', 'woodchips', 'silage', 'straw', 'grass_windrow', 'drygrass_windrow', 'sugarcane', 'fertilizer', 'pigfood', 'lime', 'snow', 'roadsalt', 'sorghum', 'grape', 'olive', 'stone', 'mineral_feed'],
	silagetrailer   : ['straw', 'grass_windrow', 'drygrass_windrow', 'chaff', 'silage', 'forage', 'woodchips', 'sugarcane'],
	slurrytank      : ['liquidmanure', 'digestate'],
	sprayer         : ['liquidfertilizer', 'herbicide'],
	spreader        : ['fertilizer'],
	trainwagon      : ['wheat', 'barley', 'oat', 'canola', 'maize', 'sunflower', 'soybean', 'sugarcane', 'sugarbeet', 'potato', 'sorghum', 'woodchips', 'olive', 'grape', 'seeds'],
	windrow         : ['straw', 'drygrass_windrow', 'grass_windrow'],
}

module.exports.alwaysArrays = {
	crop : new Set([
		'map.fruittypes.fruittype',
		'growth.seasonal.fruit',
		'growth.seasonal.fruit.period',
		'growth.seasonal.fruit.period.update',
	]),
	moddesc : new Set([
		'moddesc.actions.action',
		'moddesc.brands.brand',
		'moddesc.dependencies.dependency',
		'moddesc.inputbinding.actionbinding.binding',
		'moddesc.inputbinding.actionbinding',
		'moddesc.l10n.text',
		'moddesc.maps.map',
		'moddesc.storeitems.storeitem',
	]),
	modlook : new Set([
		'l10n.elements.e',
		'l10n.texts.text',
		'placeable.colorable.colors.color',
		'placeable.silo.storages.storage',
		'placeable.storedata.functions.function',
		'placeable.productionpoint.productions.production',
		'placeable.productionpoint.productions.production.inputs.input',
		'placeable.productionpoint.productions.production.outputs.output',
		'vehicle.base.components.component',
		'vehicle.fillunit.fillunitconfigurations.fillunitconfiguration.fillunits.fillunit',
		'vehicle.fillunit.fillunitconfigurations.fillunitconfiguration',
		'vehicle.motorized.consumerconfigurations.consumerconfiguration.consumer',
		'vehicle.motorized.consumerconfigurations',
		'vehicle.motorized.motorconfigurations.motorconfiguration',
		'vehicle.sprayer.spraytypes.spraytype',
		'vehicle.storedata.functions.function',
		'vehicle.storedata.specs.combination',
		'vehicle.wheels.wheelconfigurations.wheelconfiguration',
	]),
	savegame : new Set([
		'farms.farm',
		'placeables.placeable',
		'vehicles.vehicle',
		'careersavegame.mod',
	]),
}

module.exports.stopNodes = [
	'vehicle.animations',
	'vehicle.i3dMappings',
	'placeable.i3dMappings',
]

module.exports.getColor = (idx) => graphColors[idx % graphColors.length]

const graphColors = [
	'#4dc9f6',
	'#f67019',
	'#f53794',
	'#537bc4',
	'#acc236',
	'#166a8f',
	'#00a950',
	'#58595b',
	'#8549ba'
]