/*  _______           __ _______               __         __   
   |   |   |.-----.--|  |   _   |.-----.-----.|__|.-----.|  |_ 
   |       ||  _  |  _  |       ||__ --|__ --||  ||__ --||   _|
   |__|_|__||_____|_____|___|___||_____|_____||__||_____||____|
   (c) 2022-present FSG Modding.  MIT License. */

// Base Game data part 2

/* cSpell:disable */

const client_baseGameTopLevel = [
	{ icon : 'bg_brand',     page : 'brand',     name : 'basegame_brand'},
	{ icon : 'bg_vehicle',   page : 'vehicle',   name : 'basegame_vehicle'},
	{ icon : 'bg_tool',      page : 'tool',      name : 'basegame_tool'},
	{ icon : 'bg_object',    page : 'object',    name : 'basegame_object'},
	{ icon : 'bg_placeable', page : 'placeable', name : 'basegame_placeable'},
]

const client_baseGameCats = {
	objects : [
		{iconName : 'bigbagpallets',           title : '$l10n_category_bigbagPallets' },
		{iconName : 'bigbags',                 title : '$l10n_category_bigbags' },
		{iconName : 'pallets',                 title : '$l10n_category_pallets' },
		{iconName : 'bales',                   title : '$l10n_category_bales' },
	],
	placeables : [
		{iconName : 'animalpens',           title : '$l10n_category_animalpens' },
		{iconName : 'fences',               title : '$l10n_category_fences' },
		{iconName : 'trees',                title : '$l10n_category_trees' },
		{iconName : 'storages',             title : '$l10n_category_storages' },
		{iconName : 'containers',           title : '$l10n_category_containers' },
		{iconName : 'dieseltanks',          title : '$l10n_category_dieselTanks' },
		{iconName : 'watertanks',           title : '$l10n_category_waterTanks' },
		{iconName : 'fillabletanks',        title : '$l10n_category_fillableTanks' },
		{iconName : 'silos',                title : '$l10n_category_silos' },
		{iconName : 'siloextensions',       title : '$l10n_category_siloExtensions' },
		{iconName : 'sheds',                title : '$l10n_category_sheds' },
		{iconName : 'gardensheds',          title : '$l10n_category_gardenSheds' },
		{iconName : 'farmhouses',           title : '$l10n_category_farmhouses' },
		{iconName : 'beehives',             title : '$l10n_category_beeHives' },
		{iconName : 'generators',           title : '$l10n_category_generators' },
		{iconName : 'floodlighting',        title : '$l10n_category_floodLighting' },
		{iconName : 'decoration',           title : '$l10n_category_decoration' },
		{iconName : 'productionpoints',     title : '$l10n_category_productionPoints' },
		{iconName : 'sellingpoints',        title : '$l10n_category_sellingPoints' },
		{iconName : 'placeablemisc',        title : '$l10n_category_placeableMisc' },
	],
	tools : [
		{iconName : 'trailers',                  title : '$l10n_category_trailers' },
		{iconName : 'augerwagons',               title : '$l10n_category_augerWagons' },
		{iconName : 'cutters',                   title : '$l10n_category_cutters' },
		{iconName : 'cornheaders',               title : '$l10n_category_cornHeaders' },
		{iconName : 'forageharvestercutters',    title : '$l10n_category_forageHarvestersCutters' },
		{iconName : 'potatoharvesting',          title : '$l10n_category_potatoHarvesting' },
		{iconName : 'beetharvesting',            title : '$l10n_category_beetHarvesting' },
		{iconName : 'sugarcaneharvesting',       title : '$l10n_category_sugarCaneHarvesting' },
		{iconName : 'cottonharvesting',          title : '$l10n_category_cottonHarvesting' },
		{iconName : 'grapetools',                title : '$l10n_category_grapeVehicles' },
		{iconName : 'stonepickers',              title : '$l10n_category_stonePickers' },
		{iconName : 'mulchers',                  title : '$l10n_category_mulchers' },
		{iconName : 'plows',                     title : '$l10n_category_plows' },
		{iconName : 'cultivators',               title : '$l10n_category_cultivators' },
		{iconName : 'discharrows',               title : '$l10n_category_discHarrows' },
		{iconName : 'powerharrows',              title : '$l10n_category_powerHarrows' },
		{iconName : 'subsoilers',                title : '$l10n_category_subsoilers' },
		{iconName : 'spaders',                   title : '$l10n_category_spaders' },
		{iconName : 'seeders',                   title : '$l10n_category_sowingMachines' },
		{iconName : 'planters',                  title : '$l10n_category_planters' },
		{iconName : 'rollers',                   title : '$l10n_category_rollers' },
		{iconName : 'sprayers',                  title : '$l10n_category_sprayers' },
		{iconName : 'fertilizerspreaders',       title : '$l10n_category_fertilizerSpreaders' },
		{iconName : 'manurespreaders',           title : '$l10n_category_manureSpreaders' },
		{iconName : 'slurrytanks',               title : '$l10n_category_slurryTanks' },
		{iconName : 'weeders',                   title : '$l10n_category_weeders' },
		{iconName : 'grasslandcare',             title : '$l10n_category_grasslandCare' },
		{iconName : 'mowers',                    title : '$l10n_category_mowers' },
		{iconName : 'tedders',                   title : '$l10n_category_tedders' },
		{iconName : 'windrowers',                title : '$l10n_category_windrowers' },
		{iconName : 'loaderwagons',              title : '$l10n_category_loaderWagons' },
		{iconName : 'balers',                    title : '$l10n_category_balers' },
		{iconName : 'baleloaders',               title : '$l10n_category_baleLoaders' },
		{iconName : 'balewrappers',              title : '$l10n_category_baleWrappers' },
		{iconName : 'chainsaws',                 title : '$l10n_category_chainsaws' },
		{iconName : 'wood',                      title : '$l10n_category_wood' },
		{iconName : 'animals',                   title : '$l10n_category_animals' },
		{iconName : 'animaltransport',           title : '$l10n_category_animalTransport' },
		{iconName : 'leveler',                   title : '$l10n_category_leveler' },
		{iconName : 'silocompaction',            title : '$l10n_category_silocompaction' },
		{iconName : 'frontloaders',              title : '$l10n_category_frontLoaders' },
		{iconName : 'frontloadertools',          title : '$l10n_category_frontLoaderTools' },
		{iconName : 'wheelloadertools',          title : '$l10n_category_wheelLoaderTools' },
		{iconName : 'teleloadertools',           title : '$l10n_category_teleLoaderTools' },
		{iconName : 'skidsteertools',            title : '$l10n_category_skidSteerTools' },
		{iconName : 'dollys',                    title : '$l10n_category_dollys' },
		{iconName : 'lowloaders',                title : '$l10n_category_lowloaders' },
		{iconName : 'cuttertrailers',            title : '$l10n_category_cutterTrailers' },
		{iconName : 'weights',                   title : '$l10n_category_weights' },
		{iconName : 'belts',                     title : '$l10n_category_belts' },
		{iconName : 'winterequipment',           title : '$l10n_category_winterEquipment' },
		{iconName : 'misc',                      title : '$l10n_category_misc' },
	],
	vehicles : [
		{iconName : 'tractorss',              title : '$l10n_category_tractorsS' },
		{iconName : 'tractorsm',              title : '$l10n_category_tractorsM' },
		{iconName : 'tractorsl',              title : '$l10n_category_tractorsL' },
		{iconName : 'trucks',                 title : '$l10n_category_trucks' },
		{iconName : 'harvesters',             title : '$l10n_category_harvesters' },
		{iconName : 'forageharvesters',       title : '$l10n_category_forageHarvesters' },
		{iconName : 'potatovehicles',         title : '$l10n_category_potatoHarvesting' },
		{iconName : 'beetvehicles',           title : '$l10n_category_beetHarvesting' },
		{iconName : 'sugarcanevehicles',      title : '$l10n_category_sugarCaneHarvesting' },
		{iconName : 'cottonvehicles',         title : '$l10n_category_cottonHarvesting' },
		{iconName : 'grapevehicles',          title : '$l10n_category_grapeVehicles' },
		{iconName : 'olivevehicles',          title : '$l10n_category_oliveVehicles' },
		{iconName : 'woodharvesting',         title : '$l10n_category_woodHarvesting' },
		{iconName : 'animalsvehicles',        title : '$l10n_category_animals' },
		{iconName : 'sprayervehicles',        title : '$l10n_category_cropProtection' },
		{iconName : 'slurryvehicles',         title : '$l10n_category_slurryTanks' },
		{iconName : 'mowervehicles',          title : '$l10n_category_mowers' },
		{iconName : 'frontloadervehicles',    title : '$l10n_category_frontLoaders' },
		{iconName : 'wheelloadervehicles',    title : '$l10n_category_wheelLoaders' },
		{iconName : 'teleloadervehicles',     title : '$l10n_category_teleLoaders' },
		{iconName : 'skidsteervehicles',      title : '$l10n_category_skidSteers' },
		{iconName : 'forklifts',              title : '$l10n_category_forklifts' },
		{iconName : 'cars',                   title : '$l10n_category_cars' },
		{iconName : 'miscvehicles',           title : '$l10n_category_misc' },
	],
}

const client_baseGameCatMap_vehicle = {}
const client_baseGameCatMap_place   = {}

for ( const mainCat of ['vehicles', 'tools', 'objects'] ) {
	for ( const thisCat of client_baseGameCats[mainCat] ) { client_baseGameCatMap_vehicle[thisCat.iconName] = thisCat.title }
}
for ( const thisCat of client_baseGameCats.placeables ) { client_baseGameCatMap_place[thisCat.iconName] = thisCat.title }

const client_baseGameBrands = [
	{ name : 'abi',                       title : 'Abi',                               image : 'brand_abi' },
	{ name : 'aebi',                      title : 'AEBI',                              image : 'brand_aebi' },
	{ name : 'agco',                      title : 'AGCO',                              image : 'brand_agco' },
	{ name : 'agrisem',                   title : 'AGRISEM',                           image : 'brand_agrisem' },
	{ name : 'agromasz',                  title : 'AGROMASZ',                          image : 'brand_agromasz' },
	{ name : 'albutt',                    title : 'Albutt',                            image : 'brand_albutt' },
	{ name : 'aldi',                      title : 'ALDI GAMING',                       image : 'brand_aldi' },
	{ name : 'alpego',                    title : 'ALPEGO',                            image : 'brand_alpego' },
	{ name : 'amazone',                   title : 'AMAZONE',                           image : 'brand_amazone' },
	{ name : 'amitytech',                 title : 'AMITYTECH',                         image : 'brand_amitytechnology' },
	{ name : 'andersongroup',             title : 'Anderson Group',                    image : 'brand_andersongroup' },
	{ name : 'annaburger',                title : 'ANNABURGER',                        image : 'brand_annaburger' },
	{ name : 'apv',                       title : 'APV',                               image : 'brand_apv' },
	{ name : 'arcusin',                   title : 'Arcusin',                           image : 'brand_arcusin' },
	{ name : 'armatrac',                  title : 'Armatrac',                          image : 'brand_armatrac' },
	{ name : 'bednar',                    title : 'Bednar',                            image : 'brand_bednar' },
	{ name : 'bergmann',                  title : 'BERGMANN',                          image : 'brand_bergmann' },
	{ name : 'berthoud',                  title : 'Berthoud',                          image : 'brand_berthoud' },
	{ name : 'bkt',                       title : 'BKT',                               image : 'brand_bkt' },
	{ name : 'boeckmann',                 title : 'BÖCKMANN',                          image : 'brand_boeckmann' },
	{ name : 'bomech',                    title : 'Bomech',                            image : 'brand_bomech' },
	{ name : 'bourgault',                 title : 'BOURGAULT',                         image : 'brand_bourgault' },
	{ name : 'brantner',                  title : 'Brantner',                          image : 'brand_brantner' },
	{ name : 'bredal',                    title : 'BREDAL',                            image : 'brand_bredal' },
	{ name : 'bremer',                    title : 'Bremer',                            image : 'brand_bremer' },
	{ name : 'brielmaier',                title : 'Brielmaier',                        image : 'brand_brielmaier' },
	{ name : 'briri',                     title : 'Briri',                             image : 'brand_briri' },
	{ name : 'buehrer',                   title : 'Bührer',                            image : 'brand_buehrer' },
	{ name : 'capello',                   title : 'Capello',                           image : 'brand_capello' },
	{ name : 'caseih',                    title : 'Case IH',                           image : 'brand_caseih' },
	{ name : 'challenger',                title : 'Challenger',                        image : 'brand_challenger' },
	{ name : 'claas',                     title : 'CLAAS',                             image : 'brand_claas' },
	{ name : 'continental',               title : 'Continental',                       image : 'brand_continental' },
	{ name : 'conveyall',                 title : 'Convey-All',                        image : 'brand_conveyall' },
	{ name : 'corteva',                   title : 'Corteva',                           image : 'brand_corteva' },
	{ name : 'dalbo',                     title : 'Dalbo',                             image : 'brand_dalbo' },
	{ name : 'damcon',                    title : 'Damcon',                            image : 'brand_damcon' },
	{ name : 'degelman',                  title : 'Degelman',                          image : 'brand_degelman' },
	{ name : 'demco',                     title : 'Demco',                             image : 'brand_demco' },
	{ name : 'deutzfahr',                 title : 'DEUTZ-FAHR',                        image : 'brand_deutzfahr' },
	{ name : 'dfm',                       title : 'DFM',                               image : 'brand_dfm' },
	{ name : 'duevelsdorf',               title : 'Düvelsdorf',                        image : 'brand_duevelsdorf' },
	{ name : 'easysheds',                 title : 'EasySheds',                         image : 'brand_easysheds' },
	{ name : 'einboeck',                  title : 'Einböck',                           image : 'brand_einboeck' },
	{ name : 'elho',                      title : 'ELHO',                              image : 'brand_elho' },
	{ name : 'elmersmfg',                 title : 'Elmer\'s Manufacturing',            image : 'brand_elmersmfg' },
	{ name : 'engelbertstrauss',          title : 'Engelbert Strauss',                 image : 'brand_engelbertstrauss' },
	{ name : 'elten',                     title : 'Elten',                             image : 'brand_elten' },
	{ name : 'ero',                       title : 'ERO',                               image : 'brand_ero' },
	{ name : 'faresin',                   title : 'FARESIN',                           image : 'brand_faresin' },
	{ name : 'farmax',                    title : 'Farmax',                            image : 'brand_farmax' },
	{ name : 'farmet',                    title : 'Farmet',                            image : 'brand_farmet' },
	{ name : 'farmtech',                  title : 'Farmtech',                          image : 'brand_farmtech' },
	{ name : 'fendt',                     title : 'Fendt',                             image : 'brand_fendt' },
	{ name : 'fiat',                      title : 'Fiat',                              image : 'brand_fiat' },
	{ name : 'flexicoil',                 title : 'Flexi-Coil',                        image : 'brand_flexicoil' },
	{ name : 'fliegl',                    title : 'Fliegl',                            image : 'brand_fliegl' },
	{ name : 'fmz',                       title : 'FMŻ',                               image : 'brand_fmz' },
	{ name : 'fortschritt',               title : 'Fortschritt',                       image : 'brand_fortschritt' },
	{ name : 'fortuna',                   title : 'Fortuna',                           image : 'brand_fortuna' },
	{ name : 'fsi',                       title : 'FSI',                               image : 'brand_fsi' },
	{ name : 'fuhrmann',                  title : 'Fuhrmann',                          image : 'brand_fuhrmann' },
	{ name : 'gessner',                   title : 'Gessner Industries',                image : 'brand_gessner' },
	{ name : 'giants',                    title : 'Giants Software',                   image : 'brand_giants' },
	{ name : 'goeweil',                   title : 'GÖWEIL',                            image : 'brand_goeweil' },
	{ name : 'goldhofer',                 title : 'Goldhofer',                         image : 'brand_goldhofer' },
	{ name : 'gorenc',                    title : 'Gorenc',                            image : 'brand_gorenc' },
	{ name : 'greatplains',               title : 'Great Plains',                      image : 'brand_greatplains' },
	{ name : 'gregoirebesson',            title : 'Grégoire-Besson',                   image : 'brand_gregoirebesson' },
	{ name : 'grimme',                    title : 'Grimme',                            image : 'brand_grimme' },
	{ name : 'groha',                     title : 'GROHA',                             image : 'brand_groha' },
	{ name : 'hardi',                     title : 'Hardi',                             image : 'brand_hardi' },
	{ name : 'hatzenbichler',             title : 'Hatzenbichler',                     image : 'brand_hatzenbichler' },
	{ name : 'hauer',                     title : 'Hauer',                             image : 'brand_hauer' },
	{ name : 'hawe',                      title : 'Hawe',                              image : 'brand_hawe' },
	{ name : 'heizomat',                  title : 'Heizomat',                          image : 'brand_heizomat' },
	{ name : 'helm',                      title : 'Helm',                              image : 'brand_helm' },
	{ name : 'holaras',                   title : 'Holaras',                           image : 'brand_holaras' },
	{ name : 'holmer',                    title : 'HOLMER',                            image : 'brand_holmer' },
	{ name : 'horsch',                    title : 'HORSCH',                            image : 'brand_horsch' },
	{ name : 'husqvarna',                 title : 'Husqvarna',                         image : 'brand_husqvarna' },
	{ name : 'impex',                     title : 'IMPEX',                             image : 'brand_impex' },
	{ name : 'iseki',                     title : 'Iseki',                             image : 'brand_iseki' },
	{ name : 'jcb',                       title : 'JCB',                               image : 'brand_jcb' },
	{ name : 'jenz',                      title : 'JENZ',                              image : 'brand_jenz' },
	{ name : 'johndeere',                 title : 'John Deere',                        image : 'brand_johndeere' },
	{ name : 'jonsered',                  title : 'Jonsered',                          image : 'brand_jonsered' },
	{ name : 'joskin',                    title : 'JOSKIN',                            image : 'brand_joskin' },
	{ name : 'jungheinrich',              title : 'Jungheinrich',                      image : 'brand_jungheinrich' },
	{ name : 'kaercher',                  title : 'Kärcher',                           image : 'brand_kaercher' },
	{ name : 'kaweco',                    title : 'Kaweco',                            image : 'brand_kaweco' },
	{ name : 'kesla',                     title : 'Kesla',                             image : 'brand_kesla' },
	{ name : 'kemper',                    title : 'KEMPER',                            image : 'brand_kemper' },
	{ name : 'kingston',                  title : 'Kingston Trailers',                 image : 'brand_kingston' },
	{ name : 'kinze',                     title : 'KINZE',                             image : 'brand_kinze' },
	{ name : 'kline',                     title : 'K-Line',                            image : 'brand_kline' },
	{ name : 'knoche',                    title : 'Knoche',                            image : 'brand_knoche' },
	{ name : 'kockerling',                title : 'Köckerling',                        image : 'brand_koeckerling' },
	{ name : 'koller',                    title : 'Koller Forsttechnik',               image : 'brand_koller' },
	{ name : 'komatsu',                   title : 'Komatsu',                           image : 'brand_komatsu' },
	{ name : 'kongskilde',                title : 'Kongskilde',                        image : 'brand_kongskilde' },
	{ name : 'kotschenreuther',           title : 'Kotschenreuther',                   image : 'brand_kotschenreuther' },
	{ name : 'kotte',                     title : 'Kotte',                             image : 'brand_kotte' },
	{ name : 'kramer',                    title : 'Kramer',                            image : 'brand_kramer' },
	{ name : 'krampe',                    title : 'Krampe',                            image : 'brand_krampe' },
	{ name : 'kroeger',                   title : 'Kröger',                            image : 'brand_kroeger' },
	{ name : 'krone',                     title : 'KRONE',                             image : 'brand_krone' },
	{ name : 'kronetrailer',              title : 'KRONE Trailer',                     image : 'brand_kronetrailer' },
	{ name : 'ksag',                      title : 'K+S',                               image : 'brand_ksag' },
	{ name : 'kubota',                    title : 'Kubota',                            image : 'brand_kubota' },
	{ name : 'kuhn',                      title : 'KUHN',                              image : 'brand_kuhn' },
	{ name : 'kverneland',                title : 'Kverneland',                        image : 'brand_kverneland' },
	{ name : 'lacotec',                   title : 'Lacotec',                           image : 'brand_lacotec' },
	{ name : 'landini',                   title : 'Landini',                           image : 'brand_landini' },
	{ name : 'lely',                      title : 'Lely',                              image : 'brand_lely' },
	{ name : 'lemken',                    title : 'LEMKEN',                            image : 'brand_lemken' },
	{ name : 'lindner',                   title : 'Lindner',                           image : 'brand_lindner' },
	{ name : 'lizard',                    title : 'Lizard',                            image : 'brand_lizard' },
	{ name : 'none',                      title : 'None',                              image : 'brand_none' },
	{ name : 'lodeking',                  title : 'LODE KING',                         image : 'brand_lodeking' },
	{ name : 'mack',                      title : 'Mack Trucks',                       image : 'brand_mack' },
	{ name : 'magsi',                     title : 'MAGSI',                             image : 'brand_magsi' },
	{ name : 'mahindra',                  title : 'Mahindra',                          image : 'brand_mahindra' },
	{ name : 'man',                       title : 'MAN',                               image : 'brand_man' },
	{ name : 'manitou',                   title : 'Manitou',                           image : 'brand_manitou' },
	{ name : 'masseyferguson',            title : 'Massey Ferguson',                   image : 'brand_masseyferguson' },
	{ name : 'mccormack',                 title : 'McCormack',                         image : 'brand_mccormack' },
	{ name : 'mccormick',                 title : 'McCormick',                         image : 'brand_mccormick' },
	{ name : 'mcculloch',                 title : 'McCulloch',                         image : 'brand_mcculloch' },
	{ name : 'meridian',                  title : 'MERIDIAN',                          image : 'brand_meridian' },
	{ name : 'michelin',                  title : 'Michelin',                          image : 'brand_michelin' },
	{ name : 'michieletto',               title : 'Michieletto',                       image : 'brand_michieletto' },
	{ name : 'mitas',                     title : 'Mitas',                             image : 'brand_mitas' },
	{ name : 'nardi',                     title : 'Nardi',                             image : 'brand_nardi' },
	{ name : 'neuero',                    title : 'Neuero',                            image : 'brand_neuero' },
	{ name : 'newholland',                title : 'New Holland',                       image : 'brand_newholland' },
	{ name : 'nokian',                    title : 'Nokian',                            image : 'brand_nokian' },
	{ name : 'nordsten',                  title : 'Nordsten',                          image : 'brand_nordsten' },
	{ name : 'olofsfors',                 title : 'Olofsfors',                         image : 'brand_olofsfors' },
	{ name : 'oxbo',                      title : 'OXBO',                              image : 'brand_oxbo' },
	{ name : 'paladin',                   title : 'Paladin',                           image : 'brand_paladin' },
	{ name : 'pesslinstruments',          title : 'Pessl Instruments',                 image : 'brand_pesslinstruments' },
	{ name : 'pfanzelt',                  title : 'Pfanzelt',                          image : 'brand_pfanzelt' },
	{ name : 'pioneer',                   title : 'Pioneer',                           image : 'brand_pioneer' },
	{ name : 'planet',                    title : 'PlanET',                            image : 'brand_planet' },
	{ name : 'ploeger',                   title : 'Ploeger',                           image : 'brand_ploeger' },
	{ name : 'poettinger',                title : 'PÖTTINGER',                         image : 'brand_poettinger' },
	{ name : 'ponsse',                    title : 'PONSSE',                            image : 'brand_ponsse' },
	{ name : 'porschediesel',             title : 'Porsche Diesel',                    image : 'brand_porschediesel' },
	{ name : 'prinoth',                   title : 'Prinoth',                           image : 'brand_prinoth' },
	{ name : 'provita',                   title : 'Provita Supplements',               image : 'brand_provita' },
	{ name : 'provitis',                  title : 'Provitis',                          image : 'brand_provitis' },
	{ name : 'quicke',                    title : 'Quicke',                            image : 'brand_quicke' },
	{ name : 'rabe',                      title : 'RABE',                              image : 'brand_rabe' },
	{ name : 'randon',                    title : 'RANDON',                            image : 'brand_randon' },
	{ name : 'rau',                       title : 'Rau',                               image : 'brand_rau' },
	{ name : 'reform',                    title : 'REFORM',                            image : 'brand_reform' },
	{ name : 'reiter',                    title : 'Reiter',                            image : 'brand_reiter' },
	{ name : 'riedler',                   title : 'Riedler Fahrzeugbau',               image : 'brand_riedler' },
	{ name : 'rigitrac',                  title : 'Rigitrac',                          image : 'brand_rigitrac' },
	{ name : 'risutec',                   title : 'Risutec',                           image : 'brand_risutec' },
	{ name : 'ropa',                      title : 'Ropa',                              image : 'brand_ropa' },
	{ name : 'rostselmash',               title : 'Rostselmash',                       image : 'brand_rostselmash' },
	{ name : 'rottne',                    title : 'Rottne',                            image : 'brand_rottne' },
	{ name : 'rudolfhoermann',            title : 'Hörmann Agrarbau &amp Gewerbebau',  image : 'brand_rudolfhoermann' },
	{ name : 'rudolph',                   title : 'Rudolph',                           image : 'brand_rudolph' },
	{ name : 'salek',                     title : 'Salek',                             image : 'brand_salek' },
	{ name : 'salford',                   title : 'Salford',                           image : 'brand_salford' },
	{ name : 'samasz',                    title : 'Samasz',                            image : 'brand_samasz' },
	{ name : 'samporosenlew',             title : 'Sampo Rosenlew',                    image : 'brand_samporosenlew' },
	{ name : 'samsonagro',                title : 'Samson Agro',                       image : 'brand_samsonagro' },
	{ name : 'schaeffer',                 title : 'Schäffer',                          image : 'brand_schaeffer' },
	{ name : 'schaumann',                 title : 'Schaumann',                         image : 'brand_schaumann' },
	{ name : 'schouten',                  title : 'Schouten',                          image : 'brand_schouten' },
	{ name : 'schuitemaker',              title : 'Schuitemaker',                      image : 'brand_schuitemaker' },
	{ name : 'schwarzmueller',            title : 'Schwarzmüller',                     image : 'brand_schwarzmueller' },
	{ name : 'seppknusel',                title : 'Sepp Knüsel',                       image : 'brand_seppknuesel' },
	{ name : 'siloking',                  title : 'SILOKING',                          image : 'brand_siloking' },
	{ name : 'sip',                       title : 'SIP',                               image : 'brand_sip' },
	{ name : 'stadia',                    title : 'Stadia',                            image : 'brand_stadia' },
	{ name : 'stara',                     title : 'Stara',                             image : 'brand_stara' },
	{ name : 'starkindustries',           title : 'Stark Industries',                  image : 'brand_starkindustries' },
	{ name : 'stepa',                     title : 'STEPA',                             image : 'brand_stepa' },
	{ name : 'steyr',                     title : 'STEYR',                             image : 'brand_steyr' },
	{ name : 'stihl',                     title : 'STIHL',                             image : 'brand_stihl' },
	{ name : 'stoll',                     title : 'STOLL',                             image : 'brand_stoll' },
	{ name : 'strautmann',                title : 'Strautmann',                        image : 'brand_strautmann' },
	{ name : 'suer',                      title : 'Suer',                              image : 'brand_suer' },
	{ name : 'tajfun',                    title : 'Tajfun',                            image : 'brand_tajfun' },
	{ name : 'tatra',                     title : 'TATRA',                             image : 'brand_tatra' },
	{ name : 'tenwinkel',                 title : 'Tenwinkel',                         image : 'brand_tenwinkel' },
	{ name : 'thueringeragrar',           title : 'Thüringer Agrartechnik',            image : 'brand_thueringeragrar' },
	{ name : 'thundercreek',              title : 'Thunder Creek Equipment',           image : 'brand_thundercreek' },
	{ name : 'tmccancela',                title : 'TMC Cancela',                       image : 'brand_tmccancela' },
	{ name : 'treffler',                  title : 'Treffler',                          image : 'brand_treffler' },
	{ name : 'trelleborg',                title : 'Trelleborg',                        image : 'brand_trelleborg' },
	{ name : 'tt',                        title : 'TT',                                image : 'brand_tt' },
	{ name : 'unia',                      title : 'Unia',                              image : 'brand_unia' },
	{ name : 'unverferth',                title : 'Unverferth',                        image : 'brand_unverferth' },
	{ name : 'vaederstad',                title : 'Väderstad',                         image : 'brand_vaederstad' },
	{ name : 'valtra',                    title : 'Valtra',                            image : 'brand_valtra' },
	{ name : 'veenhuis',                  title : 'Veenhuis',                          image : 'brand_veenhuis' },
	{ name : 'vermeer',                   title : 'Vermeer',                           image : 'brand_vermeer' },
	{ name : 'versatile',                 title : 'Versatile',                         image : 'brand_versatile' },
	{ name : 'vervaet',                   title : 'Vervaet',                           image : 'brand_vervaet' },
	{ name : 'vicon',                     title : 'Vicon',                             image : 'brand_vicon' },
	{ name : 'volvo',                     title : 'Volvo',                             image : 'brand_volvo' },
	{ name : 'vredestein',                title : 'Vredestein',                        image : 'brand_vredestein' },
	{ name : 'walkabout',                 title : 'Walkabout',                         image : 'brand_walkabout' },
	{ name : 'warzee',                    title : 'Warzee',                            image : 'brand_warzee' },
	{ name : 'webermt',                   title : 'WeberMT',                           image : 'brand_webermt' },
	{ name : 'welger',                    title : 'Welger',                            image : 'brand_welger' },
	{ name : 'westtech',                  title : 'WesttecH',                          image : 'brand_westtech' },
	{ name : 'wilson',                    title : 'Wilson Trailer',                    image : 'brand_wilson' },
	{ name : 'zetor',                     title : 'Zetor',                             image : 'brand_zetor' },
	{ name : 'ziegler',                   title : 'Ziegler',                           image : 'brand_ziegler' },
	{ name : 'zunhammer',                 title : 'Zunhammer',                         image : 'brand_zunhammer' },
]


const client_baseGameBrandMap = {}
const client_baseGameBrandIconMap = {}

for ( const thisBrand of client_baseGameBrands ) {
	client_baseGameBrandMap[thisBrand.name] = thisBrand.title
	client_baseGameBrandIconMap[thisBrand.name] = thisBrand.image
}