/*  _______           __ _______               __         __   
   |   |   |.-----.--|  |   _   |.-----.-----.|__|.-----.|  |_ 
   |       ||  _  |  _  |       ||__ --|__ --||  ||__ --||   _|
   |__|_|__||_____|_____|___|___||_____|_____||__||_____||____|
   (c) 2022-present FSG Modding.  MIT License. */

// Base Game data part 2

const client_baseGameCats = {
	objects : [
		{iconName : 'bigbagpallets',           title : '$l10n_category_bigbagPallets' },
		{iconName : 'bigbags',                 title : '$l10n_category_bigbags' },
		{iconName : 'pallets',                 title : '$l10n_category_pallets' },
		{iconName : 'bales',                   title : '$l10n_category_bales' },
	],
	placeables : [
		{iconName : 'animalpens',           title : '$l10n_category_animalpens' },
		{iconName : 'fences',               title : '$l10n_category_fences' },
		{iconName : 'trees',                title : '$l10n_category_trees' },
		{iconName : 'storages',             title : '$l10n_category_storages' },
		{iconName : 'containers',           title : '$l10n_category_containers' },
		{iconName : 'dieseltanks',          title : '$l10n_category_dieselTanks' },
		{iconName : 'watertanks',           title : '$l10n_category_waterTanks' },
		{iconName : 'fillabletanks',        title : '$l10n_category_fillableTanks' },
		{iconName : 'silos',                title : '$l10n_category_silos' },
		{iconName : 'siloextensions',       title : '$l10n_category_siloExtensions' },
		{iconName : 'sheds',                title : '$l10n_category_sheds' },
		{iconName : 'gardensheds',          title : '$l10n_category_gardenSheds' },
		{iconName : 'farmhouses',           title : '$l10n_category_farmhouses' },
		{iconName : 'beehives',             title : '$l10n_category_beeHives' },
		{iconName : 'generators',           title : '$l10n_category_generators' },
		{iconName : 'floodlighting',        title : '$l10n_category_floodLighting' },
		{iconName : 'decoration',           title : '$l10n_category_decoration' },
		{iconName : 'productionpoints',     title : '$l10n_category_productionPoints' },
		{iconName : 'sellingpoints',        title : '$l10n_category_sellingPoints' },
		{iconName : 'placeablemisc',        title : '$l10n_category_placeableMisc' },
	],
	tools : [
		{iconName : 'trailers',                  title : '$l10n_category_trailers' },
		{iconName : 'augerwagons',               title : '$l10n_category_augerWagons' },
		{iconName : 'cutters',                   title : '$l10n_category_cutters' },
		{iconName : 'cornheaders',               title : '$l10n_category_cornHeaders' },
		{iconName : 'forageharvestercutters',    title : '$l10n_category_forageHarvestersCutters' },
		{iconName : 'potatoharvesting',          title : '$l10n_category_potatoHarvesting' },
		{iconName : 'beetharvesting',            title : '$l10n_category_beetHarvesting' },
		{iconName : 'sugarcaneharvesting',       title : '$l10n_category_sugarCaneHarvesting' },
		{iconName : 'cottonharvesting',          title : '$l10n_category_cottonHarvesting' },
		{iconName : 'grapetools',                title : '$l10n_category_grapeVehicles' },
		{iconName : 'stonepickers',              title : '$l10n_category_stonePickers' },
		{iconName : 'mulchers',                  title : '$l10n_category_mulchers' },
		{iconName : 'plows',                     title : '$l10n_category_plows' },
		{iconName : 'cultivators',               title : '$l10n_category_cultivators' },
		{iconName : 'discharrows',               title : '$l10n_category_discHarrows' },
		{iconName : 'powerharrows',              title : '$l10n_category_powerHarrows' },
		{iconName : 'subsoilers',                title : '$l10n_category_subsoilers' },
		{iconName : 'spaders',                   title : '$l10n_category_spaders' },
		{iconName : 'seeders',                   title : '$l10n_category_sowingMachines' },
		{iconName : 'planters',                  title : '$l10n_category_planters' },
		{iconName : 'rollers',                   title : '$l10n_category_rollers' },
		{iconName : 'sprayers',                  title : '$l10n_category_sprayers' },
		{iconName : 'fertilizerspreaders',       title : '$l10n_category_fertilizerSpreaders' },
		{iconName : 'manurespreaders',           title : '$l10n_category_manureSpreaders' },
		{iconName : 'slurrytanks',               title : '$l10n_category_slurryTanks' },
		{iconName : 'weeders',                   title : '$l10n_category_weeders' },
		{iconName : 'grasslandcare',             title : '$l10n_category_grasslandCare' },
		{iconName : 'mowers',                    title : '$l10n_category_mowers' },
		{iconName : 'tedders',                   title : '$l10n_category_tedders' },
		{iconName : 'windrowers',                title : '$l10n_category_windrowers' },
		{iconName : 'loaderwagons',              title : '$l10n_category_loaderWagons' },
		{iconName : 'balers',                    title : '$l10n_category_balers' },
		{iconName : 'baleloaders',               title : '$l10n_category_baleLoaders' },
		{iconName : 'balewrappers',              title : '$l10n_category_baleWrappers' },
		{iconName : 'chainsaws',                 title : '$l10n_category_chainsaws' },
		{iconName : 'wood',                      title : '$l10n_category_wood' },
		{iconName : 'animals',                   title : '$l10n_category_animals' },
		{iconName : 'animaltransport',           title : '$l10n_category_animalTransport' },
		{iconName : 'leveler',                   title : '$l10n_category_leveler' },
		{iconName : 'silocompaction',            title : '$l10n_category_silocompaction' },
		{iconName : 'frontloaders',              title : '$l10n_category_frontLoaders' },
		{iconName : 'frontloadertools',          title : '$l10n_category_frontLoaderTools' },
		{iconName : 'wheelloadertools',          title : '$l10n_category_wheelLoaderTools' },
		{iconName : 'teleloadertools',           title : '$l10n_category_teleLoaderTools' },
		{iconName : 'skidsteertools',            title : '$l10n_category_skidSteerTools' },
		{iconName : 'dollys',                    title : '$l10n_category_dollys' },
		{iconName : 'lowloaders',                title : '$l10n_category_lowloaders' },
		{iconName : 'cuttertrailers',            title : '$l10n_category_cutterTrailers' },
		{iconName : 'weights',                   title : '$l10n_category_weights' },
		{iconName : 'belts',                     title : '$l10n_category_belts' },
		{iconName : 'winterequipment',           title : '$l10n_category_winterEquipment' },
		{iconName : 'misc',                      title : '$l10n_category_misc' },
	],
	vehicles : [
		{iconName : 'tractorss',              title : '$l10n_category_tractorsS' },
		{iconName : 'tractorsm',              title : '$l10n_category_tractorsM' },
		{iconName : 'tractorsl',              title : '$l10n_category_tractorsL' },
		{iconName : 'trucks',                 title : '$l10n_category_trucks' },
		{iconName : 'harvesters',             title : '$l10n_category_harvesters' },
		{iconName : 'forageharvesters',       title : '$l10n_category_forageHarvesters' },
		{iconName : 'potatovehicles',         title : '$l10n_category_potatoHarvesting' },
		{iconName : 'beetvehicles',           title : '$l10n_category_beetHarvesting' },
		{iconName : 'sugarcanevehicles',      title : '$l10n_category_sugarCaneHarvesting' },
		{iconName : 'cottonvehicles',         title : '$l10n_category_cottonHarvesting' },
		{iconName : 'grapevehicles',          title : '$l10n_category_grapeVehicles' },
		{iconName : 'olivevehicles',          title : '$l10n_category_oliveVehicles' },
		{iconName : 'woodharvesting',         title : '$l10n_category_woodHarvesting' },
		{iconName : 'animalsvehicles',        title : '$l10n_category_animals' },
		{iconName : 'sprayervehicles',        title : '$l10n_category_cropProtection' },
		{iconName : 'slurryvehicles',         title : '$l10n_category_slurryTanks' },
		{iconName : 'mowervehicles',          title : '$l10n_category_mowers' },
		{iconName : 'frontloadervehicles',    title : '$l10n_category_frontLoaders' },
		{iconName : 'wheelloadervehicles',    title : '$l10n_category_wheelLoaders' },
		{iconName : 'teleloadervehicles',     title : '$l10n_category_teleLoaders' },
		{iconName : 'skidsteervehicles',      title : '$l10n_category_skidSteers' },
		{iconName : 'forklifts',              title : '$l10n_category_forklifts' },
		{iconName : 'cars',                   title : '$l10n_category_cars' },
		{iconName : 'miscvehicles',           title : '$l10n_category_misc' },
	],
}