/*  _______           __ _______               __         __   
   |   |   |.-----.--|  |   _   |.-----.-----.|__|.-----.|  |_ 
   |       ||  _  |  _  |       ||__ --|__ --||  ||__ --||   _|
   |__|_|__||_____|_____|___|___||_____|_____||__||_____||____|
   (c) 2022-present FSG Modding.  MIT License. */

// Base Game data part 2

/* cSpell:disable */

const client_baseGameCats = {
	objects : [
		{iconName : 'bigbagpallets',           title : '$l10n_category_bigbagPallets' },
		{iconName : 'bigbags',                 title : '$l10n_category_bigbags' },
		{iconName : 'pallets',                 title : '$l10n_category_pallets' },
		{iconName : 'bales',                   title : '$l10n_category_bales' },
	],
	placeables : [
		{iconName : 'animalpens',           title : '$l10n_category_animalpens' },
		{iconName : 'fences',               title : '$l10n_category_fences' },
		{iconName : 'trees',                title : '$l10n_category_trees' },
		{iconName : 'storages',             title : '$l10n_category_storages' },
		{iconName : 'containers',           title : '$l10n_category_containers' },
		{iconName : 'dieseltanks',          title : '$l10n_category_dieselTanks' },
		{iconName : 'watertanks',           title : '$l10n_category_waterTanks' },
		{iconName : 'fillabletanks',        title : '$l10n_category_fillableTanks' },
		{iconName : 'silos',                title : '$l10n_category_silos' },
		{iconName : 'siloextensions',       title : '$l10n_category_siloExtensions' },
		{iconName : 'sheds',                title : '$l10n_category_sheds' },
		{iconName : 'gardensheds',          title : '$l10n_category_gardenSheds' },
		{iconName : 'farmhouses',           title : '$l10n_category_farmhouses' },
		{iconName : 'beehives',             title : '$l10n_category_beeHives' },
		{iconName : 'generators',           title : '$l10n_category_generators' },
		{iconName : 'floodlighting',        title : '$l10n_category_floodLighting' },
		{iconName : 'decoration',           title : '$l10n_category_decoration' },
		{iconName : 'productionpoints',     title : '$l10n_category_productionPoints' },
		{iconName : 'sellingpoints',        title : '$l10n_category_sellingPoints' },
		{iconName : 'placeablemisc',        title : '$l10n_category_placeableMisc' },
	],
	tools : [
		{iconName : 'trailers',                  title : '$l10n_category_trailers' },
		{iconName : 'augerwagons',               title : '$l10n_category_augerWagons' },
		{iconName : 'cutters',                   title : '$l10n_category_cutters' },
		{iconName : 'cornheaders',               title : '$l10n_category_cornHeaders' },
		{iconName : 'forageharvestercutters',    title : '$l10n_category_forageHarvestersCutters' },
		{iconName : 'potatoharvesting',          title : '$l10n_category_potatoHarvesting' },
		{iconName : 'beetharvesting',            title : '$l10n_category_beetHarvesting' },
		{iconName : 'sugarcaneharvesting',       title : '$l10n_category_sugarCaneHarvesting' },
		{iconName : 'cottonharvesting',          title : '$l10n_category_cottonHarvesting' },
		{iconName : 'grapetools',                title : '$l10n_category_grapeVehicles' },
		{iconName : 'stonepickers',              title : '$l10n_category_stonePickers' },
		{iconName : 'mulchers',                  title : '$l10n_category_mulchers' },
		{iconName : 'plows',                     title : '$l10n_category_plows' },
		{iconName : 'cultivators',               title : '$l10n_category_cultivators' },
		{iconName : 'discharrows',               title : '$l10n_category_discHarrows' },
		{iconName : 'powerharrows',              title : '$l10n_category_powerHarrows' },
		{iconName : 'subsoilers',                title : '$l10n_category_subsoilers' },
		{iconName : 'spaders',                   title : '$l10n_category_spaders' },
		{iconName : 'seeders',                   title : '$l10n_category_sowingMachines' },
		{iconName : 'planters',                  title : '$l10n_category_planters' },
		{iconName : 'rollers',                   title : '$l10n_category_rollers' },
		{iconName : 'sprayers',                  title : '$l10n_category_sprayers' },
		{iconName : 'fertilizerspreaders',       title : '$l10n_category_fertilizerSpreaders' },
		{iconName : 'manurespreaders',           title : '$l10n_category_manureSpreaders' },
		{iconName : 'slurrytanks',               title : '$l10n_category_slurryTanks' },
		{iconName : 'weeders',                   title : '$l10n_category_weeders' },
		{iconName : 'grasslandcare',             title : '$l10n_category_grasslandCare' },
		{iconName : 'mowers',                    title : '$l10n_category_mowers' },
		{iconName : 'tedders',                   title : '$l10n_category_tedders' },
		{iconName : 'windrowers',                title : '$l10n_category_windrowers' },
		{iconName : 'loaderwagons',              title : '$l10n_category_loaderWagons' },
		{iconName : 'balers',                    title : '$l10n_category_balers' },
		{iconName : 'baleloaders',               title : '$l10n_category_baleLoaders' },
		{iconName : 'balewrappers',              title : '$l10n_category_baleWrappers' },
		{iconName : 'chainsaws',                 title : '$l10n_category_chainsaws' },
		{iconName : 'wood',                      title : '$l10n_category_wood' },
		{iconName : 'animals',                   title : '$l10n_category_animals' },
		{iconName : 'animaltransport',           title : '$l10n_category_animalTransport' },
		{iconName : 'leveler',                   title : '$l10n_category_leveler' },
		{iconName : 'silocompaction',            title : '$l10n_category_silocompaction' },
		{iconName : 'frontloaders',              title : '$l10n_category_frontLoaders' },
		{iconName : 'frontloadertools',          title : '$l10n_category_frontLoaderTools' },
		{iconName : 'wheelloadertools',          title : '$l10n_category_wheelLoaderTools' },
		{iconName : 'teleloadertools',           title : '$l10n_category_teleLoaderTools' },
		{iconName : 'skidsteertools',            title : '$l10n_category_skidSteerTools' },
		{iconName : 'dollys',                    title : '$l10n_category_dollys' },
		{iconName : 'lowloaders',                title : '$l10n_category_lowloaders' },
		{iconName : 'cuttertrailers',            title : '$l10n_category_cutterTrailers' },
		{iconName : 'weights',                   title : '$l10n_category_weights' },
		{iconName : 'belts',                     title : '$l10n_category_belts' },
		{iconName : 'winterequipment',           title : '$l10n_category_winterEquipment' },
		{iconName : 'misc',                      title : '$l10n_category_misc' },
	],
	vehicles : [
		{iconName : 'tractorss',              title : '$l10n_category_tractorsS' },
		{iconName : 'tractorsm',              title : '$l10n_category_tractorsM' },
		{iconName : 'tractorsl',              title : '$l10n_category_tractorsL' },
		{iconName : 'trucks',                 title : '$l10n_category_trucks' },
		{iconName : 'harvesters',             title : '$l10n_category_harvesters' },
		{iconName : 'forageharvesters',       title : '$l10n_category_forageHarvesters' },
		{iconName : 'potatovehicles',         title : '$l10n_category_potatoHarvesting' },
		{iconName : 'beetvehicles',           title : '$l10n_category_beetHarvesting' },
		{iconName : 'sugarcanevehicles',      title : '$l10n_category_sugarCaneHarvesting' },
		{iconName : 'cottonvehicles',         title : '$l10n_category_cottonHarvesting' },
		{iconName : 'grapevehicles',          title : '$l10n_category_grapeVehicles' },
		{iconName : 'olivevehicles',          title : '$l10n_category_oliveVehicles' },
		{iconName : 'woodharvesting',         title : '$l10n_category_woodHarvesting' },
		{iconName : 'animalsvehicles',        title : '$l10n_category_animals' },
		{iconName : 'sprayervehicles',        title : '$l10n_category_cropProtection' },
		{iconName : 'slurryvehicles',         title : '$l10n_category_slurryTanks' },
		{iconName : 'mowervehicles',          title : '$l10n_category_mowers' },
		{iconName : 'frontloadervehicles',    title : '$l10n_category_frontLoaders' },
		{iconName : 'wheelloadervehicles',    title : '$l10n_category_wheelLoaders' },
		{iconName : 'teleloadervehicles',     title : '$l10n_category_teleLoaders' },
		{iconName : 'skidsteervehicles',      title : '$l10n_category_skidSteers' },
		{iconName : 'forklifts',              title : '$l10n_category_forklifts' },
		{iconName : 'cars',                   title : '$l10n_category_cars' },
		{iconName : 'miscvehicles',           title : '$l10n_category_misc' },
	],
}

const client_baseGameBrands = [
	{ title : 'Abi',                               image : 'brand_abi' },
	{ title : 'AEBI',                              image : 'brand_aebi' },
	{ title : 'AGCO',                              image : 'brand_agco' },
	{ title : 'AGRISEM',                           image : 'brand_agrisem' },
	{ title : 'AGROMASZ',                          image : 'brand_agromasz' },
	{ title : 'Albutt',                            image : 'brand_albutt' },
	{ title : 'ALDI GAMING',                       image : 'brand_aldi' },
	{ title : 'ALPEGO',                            image : 'brand_alpego' },
	{ title : 'AMAZONE',                           image : 'brand_amazone' },
	{ title : 'AMITYTECH',                         image : 'brand_amitytechnology' },
	{ title : 'Anderson Group',                    image : 'brand_andersongroup' },
	{ title : 'ANNABURGER',                        image : 'brand_annaburger' },
	{ title : 'APV',                               image : 'brand_apv' },
	{ title : 'Arcusin',                           image : 'brand_arcusin' },
	{ title : 'Armatrac',                          image : 'brand_armatrac' },
	{ title : 'Bednar',                            image : 'brand_bednar' },
	{ title : 'BERGMANN',                          image : 'brand_bergmann' },
	{ title : 'Berthoud',                          image : 'brand_berthoud' },
	{ title : 'BKT',                               image : 'brand_bkt' },
	{ title : 'BÖCKMANN',                          image : 'brand_boeckmann' },
	{ title : 'Bomech',                            image : 'brand_bomech' },
	{ title : 'BOURGAULT',                         image : 'brand_bourgault' },
	{ title : 'Brantner',                          image : 'brand_brantner' },
	{ title : 'BREDAL',                            image : 'brand_bredal' },
	{ title : 'Bremer',                            image : 'brand_bremer' },
	{ title : 'Brielmaier',                        image : 'brand_brielmaier' },
	{ title : 'Briri',                             image : 'brand_briri' },
	{ title : 'Bührer',                            image : 'brand_buehrer' },
	{ title : 'Capello',                           image : 'brand_capello' },
	{ title : 'Case IH',                           image : 'brand_caseih' },
	{ title : 'Challenger',                        image : 'brand_challenger' },
	{ title : 'CLAAS',                             image : 'brand_claas' },
	{ title : 'Continental',                       image : 'brand_continental' },
	{ title : 'Convey-All',                        image : 'brand_conveyall' },
	{ title : 'Corteva',                           image : 'brand_corteva' },
	{ title : 'Dalbo',                             image : 'brand_dalbo' },
	{ title : 'Damcon',                            image : 'brand_damcon' },
	{ title : 'Degelman',                          image : 'brand_degelman' },
	{ title : 'Demco',                             image : 'brand_demco' },
	{ title : 'DEUTZ-FAHR',                        image : 'brand_deutzfahr' },
	{ title : 'DFM',                               image : 'brand_dfm' },
	{ title : 'Düvelsdorf',                        image : 'brand_duevelsdorf' },
	{ title : 'EasySheds',                         image : 'brand_easysheds' },
	{ title : 'Einböck',                           image : 'brand_einboeck' },
	{ title : 'ELHO',                              image : 'brand_elho' },
	{ title : 'Elmer\'s Manufacturing',            image : 'brand_elmersmfg' },
	{ title : 'Engelbert Strauss',                 image : 'brand_engelbertstrauss' },
	{ title : 'Elten',                             image : 'brand_elten' },
	{ title : 'ERO',                               image : 'brand_ero' },
	{ title : 'FARESIN',                           image : 'brand_faresin' },
	{ title : 'Farmax',                            image : 'brand_farmax' },
	{ title : 'Farmet',                            image : 'brand_farmet' },
	{ title : 'Farmtech',                          image : 'brand_farmtech' },
	{ title : 'Fendt',                             image : 'brand_fendt' },
	{ title : 'Fiat',                              image : 'brand_fiat' },
	{ title : 'Flexi-Coil',                        image : 'brand_flexicoil' },
	{ title : 'Fliegl',                            image : 'brand_fliegl' },
	{ title : 'FMŻ',                               image : 'brand_fmz' },
	{ title : 'Fortschritt',                       image : 'brand_fortschritt' },
	{ title : 'Fortuna',                           image : 'brand_fortuna' },
	{ title : 'FSI',                               image : 'brand_fsi' },
	{ title : 'Fuhrmann',                          image : 'brand_fuhrmann' },
	{ title : 'Gessner Industries',                image : 'brand_gessner' },
	{ title : 'Giants Software',                   image : 'brand_giants' },
	{ title : 'GÖWEIL',                            image : 'brand_goeweil' },
	{ title : 'Goldhofer',                         image : 'brand_goldhofer' },
	{ title : 'Gorenc',                            image : 'brand_gorenc' },
	{ title : 'Great Plains',                      image : 'brand_greatplains' },
	{ title : 'Grégoire-Besson',                   image : 'brand_gregoirebesson' },
	{ title : 'Grimme',                            image : 'brand_grimme' },
	{ title : 'GROHA',                             image : 'brand_groha' },
	{ title : 'Hardi',                             image : 'brand_hardi' },
	{ title : 'Hatzenbichler',                     image : 'brand_hatzenbichler' },
	{ title : 'Hauer',                             image : 'brand_hauer' },
	{ title : 'Hawe',                              image : 'brand_hawe' },
	{ title : 'Heizomat',                          image : 'brand_heizomat' },
	{ title : 'Helm',                              image : 'brand_helm' },
	{ title : 'Holaras',                           image : 'brand_holaras' },
	{ title : 'HOLMER',                            image : 'brand_holmer' },
	{ title : 'HORSCH',                            image : 'brand_horsch' },
	{ title : 'Husqvarna',                         image : 'brand_husqvarna' },
	{ title : 'IMPEX',                             image : 'brand_impex' },
	{ title : 'Iseki',                             image : 'brand_iseki' },
	{ title : 'JCB',                               image : 'brand_jcb' },
	{ title : 'JENZ',                              image : 'brand_jenz' },
	{ title : 'John Deere',                        image : 'brand_johndeere' },
	{ title : 'Jonsered',                          image : 'brand_jonsered' },
	{ title : 'JOSKIN',                            image : 'brand_joskin' },
	{ title : 'Jungheinrich',                      image : 'brand_jungheinrich' },
	{ title : 'Kärcher',                           image : 'brand_kaercher' },
	{ title : 'Kaweco',                            image : 'brand_kaweco' },
	{ title : 'Kesla',                             image : 'brand_kesla' },
	{ title : 'KEMPER',                            image : 'brand_kemper' },
	{ title : 'Kingston Trailers',                 image : 'brand_kingston' },
	{ title : 'KINZE',                             image : 'brand_kinze' },
	{ title : 'K-Line',                            image : 'brand_kline' },
	{ title : 'Knoche',                            image : 'brand_knoche' },
	{ title : 'Köckerling',                        image : 'brand_koeckerling' },
	{ title : 'Koller Forsttechnik',               image : 'brand_koller' },
	{ title : 'Komatsu',                           image : 'brand_komatsu' },
	{ title : 'Kongskilde',                        image : 'brand_kongskilde' },
	{ title : 'Kotschenreuther',                   image : 'brand_kotschenreuther' },
	{ title : 'Kotte',                             image : 'brand_kotte' },
	{ title : 'Kramer',                            image : 'brand_kramer' },
	{ title : 'Krampe',                            image : 'brand_krampe' },
	{ title : 'Kröger',                            image : 'brand_kroeger' },
	{ title : 'KRONE',                             image : 'brand_krone' },
	{ title : 'KRONE Trailer',                     image : 'brand_kronetrailer' },
	{ title : 'K+S',                               image : 'brand_ksag' },
	{ title : 'Kubota',                            image : 'brand_kubota' },
	{ title : 'KUHN',                              image : 'brand_kuhn' },
	{ title : 'Kverneland',                        image : 'brand_kverneland' },
	{ title : 'Lacotec',                           image : 'brand_lacotec' },
	{ title : 'Landini',                           image : 'brand_landini' },
	{ title : 'Lely',                              image : 'brand_lely' },
	{ title : 'LEMKEN',                            image : 'brand_lemken' },
	{ title : 'Lindner',                           image : 'brand_lindner' },
	{ title : 'Lizard',                            image : 'brand_lizard' },
	{ title : 'None',                              image : 'brand_none' },
	{ title : 'LODE KING',                         image : 'brand_lodeking' },
	{ title : 'Mack Trucks',                       image : 'brand_mack' },
	{ title : 'MAGSI',                             image : 'brand_magsi' },
	{ title : 'Mahindra',                          image : 'brand_mahindra' },
	{ title : 'MAN',                               image : 'brand_man' },
	{ title : 'Manitou',                           image : 'brand_manitou' },
	{ title : 'Massey Ferguson',                   image : 'brand_masseyferguson' },
	{ title : 'McCormack',                         image : 'brand_mccormack' },
	{ title : 'McCormick',                         image : 'brand_mccormick' },
	{ title : 'McCulloch',                         image : 'brand_mcculloch' },
	{ title : 'MERIDIAN',                          image : 'brand_meridian' },
	{ title : 'Michelin',                          image : 'brand_michelin' },
	{ title : 'Michieletto',                       image : 'brand_michieletto' },
	{ title : 'Mitas',                             image : 'brand_mitas' },
	{ title : 'Nardi',                             image : 'brand_nardi' },
	{ title : 'Neuero',                            image : 'brand_neuero' },
	{ title : 'New Holland',                       image : 'brand_newholland' },
	{ title : 'Nokian',                            image : 'brand_nokian' },
	{ title : 'Nordsten',                          image : 'brand_nordsten' },
	{ title : 'Olofsfors',                         image : 'brand_olofsfors' },
	{ title : 'OXBO',                              image : 'brand_oxbo' },
	{ title : 'Paladin',                           image : 'brand_paladin' },
	{ title : 'Pessl Instruments',                 image : 'brand_pesslinstruments' },
	{ title : 'Pfanzelt',                          image : 'brand_pfanzelt' },
	{ title : 'Pioneer',                           image : 'brand_pioneer' },
	{ title : 'PlanET',                            image : 'brand_planet' },
	{ title : 'Ploeger',                           image : 'brand_ploeger' },
	{ title : 'PÖTTINGER',                         image : 'brand_poettinger' },
	{ title : 'PONSSE',                            image : 'brand_ponsse' },
	{ title : 'Porsche Diesel',                    image : 'brand_porschediesel' },
	{ title : 'Prinoth',                           image : 'brand_prinoth' },
	{ title : 'Provita Supplements',               image : 'brand_provita' },
	{ title : 'Provitis',                          image : 'brand_provitis' },
	{ title : 'Quicke',                            image : 'brand_quicke' },
	{ title : 'RABE',                              image : 'brand_rabe' },
	{ title : 'RANDON',                            image : 'brand_randon' },
	{ title : 'Rau',                               image : 'brand_rau' },
	{ title : 'REFORM',                            image : 'brand_reform' },
	{ title : 'Reiter',                            image : 'brand_reiter' },
	{ title : 'Riedler Fahrzeugbau',               image : 'brand_riedler' },
	{ title : 'Rigitrac',                          image : 'brand_rigitrac' },
	{ title : 'Risutec',                           image : 'brand_risutec' },
	{ title : 'Ropa',                              image : 'brand_ropa' },
	{ title : 'Rostselmash',                       image : 'brand_rostselmash' },
	{ title : 'Rottne',                            image : 'brand_rottne' },
	{ title : 'Hörmann Agrarbau &amp; Gewerbebau', image : 'brand_rudolfhoermann' },
	{ title : 'Rudolph',                           image : 'brand_rudolph' },
	{ title : 'Salek',                             image : 'brand_salek' },
	{ title : 'Salford',                           image : 'brand_salford' },
	{ title : 'Samasz',                            image : 'brand_samasz' },
	{ title : 'Sampo Rosenlew',                    image : 'brand_samporosenlew' },
	{ title : 'Samson Agro',                       image : 'brand_samsonagro' },
	{ title : 'Schäffer',                          image : 'brand_schaeffer' },
	{ title : 'Schaumann',                         image : 'brand_schaumann' },
	{ title : 'Schouten',                          image : 'brand_schouten' },
	{ title : 'Schuitemaker',                      image : 'brand_schuitemaker' },
	{ title : 'Schwarzmüller',                     image : 'brand_schwarzmueller' },
	{ title : 'Sepp Knüsel',                       image : 'brand_seppknuesel' },
	{ title : 'SILOKING',                          image : 'brand_siloking' },
	{ title : 'SIP',                               image : 'brand_sip' },
	{ title : 'Stadia',                            image : 'brand_stadia' },
	{ title : 'Stara',                             image : 'brand_stara' },
	{ title : 'Stark Industries',                  image : 'brand_starkindustries' },
	{ title : 'STEPA',                             image : 'brand_stepa' },
	{ title : 'STEYR',                             image : 'brand_steyr' },
	{ title : 'STIHL',                             image : 'brand_stihl' },
	{ title : 'STOLL',                             image : 'brand_stoll' },
	{ title : 'Strautmann',                        image : 'brand_strautmann' },
	{ title : 'Suer',                              image : 'brand_suer' },
	{ title : 'Tajfun',                            image : 'brand_tajfun' },
	{ title : 'TATRA',                             image : 'brand_tatra' },
	{ title : 'Tenwinkel',                         image : 'brand_tenwinkel' },
	{ title : 'Thüringer Agrartechnik',            image : 'brand_thueringeragrar' },
	{ title : 'Thunder Creek Equipment',           image : 'brand_thundercreek' },
	{ title : 'TMC Cancela',                       image : 'brand_tmccancela' },
	{ title : 'Treffler',                          image : 'brand_treffler' },
	{ title : 'Trelleborg',                        image : 'brand_trelleborg' },
	{ title : 'TT',                                image : 'brand_tt' },
	{ title : 'Unia',                              image : 'brand_unia' },
	{ title : 'Unverferth',                        image : 'brand_unverferth' },
	{ title : 'Väderstad',                         image : 'brand_vaederstad' },
	{ title : 'Valtra',                            image : 'brand_valtra' },
	{ title : 'Veenhuis',                          image : 'brand_veenhuis' },
	{ title : 'Vermeer',                           image : 'brand_vermeer' },
	{ title : 'Versatile',                         image : 'brand_versatile' },
	{ title : 'Vervaet',                           image : 'brand_vervaet' },
	{ title : 'Vicon',                             image : 'brand_vicon' },
	{ title : 'Volvo',                             image : 'brand_volvo' },
	{ title : 'Vredestein',                        image : 'brand_vredestein' },
	{ title : 'Walkabout',                         image : 'brand_walkabout' },
	{ title : 'Warzee',                            image : 'brand_warzee' },
	{ title : 'WeberMT',                           image : 'brand_webermt' },
	{ title : 'Welger',                            image : 'brand_welger' },
	{ title : 'WesttecH',                          image : 'brand_westtech' },
	{ title : 'Wilson Trailer',                    image : 'brand_wilson' },
	{ title : 'Zetor',                             image : 'brand_zetor' },
	{ title : 'Ziegler',                           image : 'brand_ziegler' },
	{ title : 'Zunhammer',                         image : 'brand_zunhammer' },
]