function clientGetKeyMapSimple(keys) {
	return keys.split(' ').map((key) => { return getKeyMap(key)} ).join('+')
}
function clientGetKeyMap(keys) {
	return keys.split('--')[1].split(' ').map((key) => { return getKeyMap(key)}).join('+')
}
function getKeyMap(key) {
	return `<span class="btn disabled btn-sm btn-outline-light small">${keyMap[key]}</span>`
}
const keyMap = {
	'AXIS_X+'                 : 'Axis X+',
	'AXIS_Y+'                 : 'Axis Y+',
	'AXIS_X-'                 : 'Axis X-',
	'AXIS_Y-'                 : 'Axis Y-',
	'KEY_backspace'           : 'BKSPC',
	'KEY_tab'                 : 'TAB',
	'KEY_clear'               : 'CLEAR',
	'KEY_return'              : 'RETURN',
	'KEY_pause'               : 'PAUSE',
	'KEY_esc'                 : 'ESC',
	'KEY_space'               : 'SPACE',
	'KEY_exclaim'             : '!',
	'KEY_quotedbl'            : '"',
	'KEY_hash'                : '#',
	'KEY_dollar'              : '$',
	'KEY_ampersand'           : '&',
	'KEY_quote'               : '\'',
	'KEY_leftparen'           : '[',
	'KEY_rightparen'          : ']',
	'KEY_asterisk'            : '*',
	'KEY_plus'                : '+',
	'KEY_comma'               : ',',
	'KEY_minus'               : '-',
	'KEY_period'              : '.',
	'KEY_slash'               : '/',
	'KEY_0'                   : '0',
	'KEY_1'                   : '1',
	'KEY_2'                   : '2',
	'KEY_3'                   : '3',
	'KEY_4'                   : '4',
	'KEY_5'                   : '5',
	'KEY_6'                   : '6',
	'KEY_7'                   : '7',
	'KEY_8'                   : '8',
	'KEY_9'                   : '9',
	'KEY_colon'               : ':',
	'KEY_semicolon'           : ';',
	'KEY_less'                : '<',
	'KEY_equals'              : '=',
	'KEY_greater'             : '>',
	'KEY_question'            : '?',
	'KEY_at'                  : '@',
	'KEY_leftbracket'         : '{',
	'KEY_backslash'           : '\\',
	'KEY_rightbracket'        : '}',
	'KEY_caret'               : '~',
	'KEY_underscore'          : '_',
	'KEY_backquote'           : '`',
	'KEY_a'                   : 'A',
	'KEY_b'                   : 'B',
	'KEY_c'                   : 'C',
	'KEY_d'                   : 'D',
	'KEY_e'                   : 'E',
	'KEY_f'                   : 'F',
	'KEY_g'                   : 'G',
	'KEY_h'                   : 'H',
	'KEY_i'                   : 'I',
	'KEY_j'                   : 'J',
	'KEY_k'                   : 'K',
	'KEY_l'                   : 'L',
	'KEY_m'                   : 'M',
	'KEY_n'                   : 'N',
	'KEY_o'                   : 'O',
	'KEY_p'                   : 'P',
	'KEY_q'                   : 'Q',
	'KEY_r'                   : 'R',
	'KEY_s'                   : 'S',
	'KEY_t'                   : 'T',
	'KEY_u'                   : 'U',
	'KEY_v'                   : 'V',
	'KEY_w'                   : 'W',
	'KEY_x'                   : 'X',
	'KEY_y'                   : 'Y',
	'KEY_z'                   : 'Z',
	'KEY_delete'              : 'DEL',
	'KEY_KP_0'                : 'NumPad 0',
	'KEY_KP_1'                : 'NumPad 1',
	'KEY_KP_2'                : 'NumPad 2',
	'KEY_KP_3'                : 'NumPad 3',
	'KEY_KP_4'                : 'NumPad 4',
	'KEY_KP_5'                : 'NumPad 5',
	'KEY_KP_6'                : 'NumPad 6',
	'KEY_KP_7'                : 'NumPad 7',
	'KEY_KP_8'                : 'NumPad 8',
	'KEY_KP_9'                : 'NumPad 9',
	'KEY_KP_period'           : 'NumPad .',
	'KEY_KP_divide'           : 'NumPad /',
	'KEY_KP_multiply'         : 'NumPad *',
	'KEY_KP_minus'            : 'NumPad -',
	'KEY_KP_plus'             : 'NumPad +',
	'KEY_KP_enter'            : 'NumPad ENTER',
	'KEY_KP_equals'           : 'NumPad =',
	'KEY_up'                  : '↑',
	'KEY_down'                : '↓',
	'KEY_right'               : '→',
	'KEY_left'                : '←',
	'KEY_insert'              : 'INS',
	'KEY_home'                : 'HOME',
	'KEY_end'                 : 'END',
	'KEY_pageup'              : 'PgUp',
	'KEY_pagedown'            : 'PgDown',
	'KEY_f1'                  : 'F1',
	'KEY_f2'                  : 'F2',
	'KEY_f3'                  : 'F3',
	'KEY_f4'                  : 'F4',
	'KEY_f5'                  : 'F5',
	'KEY_f6'                  : 'F6',
	'KEY_f7'                  : 'F7',
	'KEY_f8'                  : 'F8',
	'KEY_f9'                  : 'F9',
	'KEY_f10'                 : 'F10',
	'KEY_f11'                 : 'F11',
	'KEY_f12'                 : 'F12',
	'KEY_f13'                 : 'F13',
	'KEY_f14'                 : 'F14',
	'KEY_f15'                 : 'F15',
	'KEY_rshift'              : 'Right SHIFT',
	'KEY_lshift'              : 'Left SHIFT',
	'KEY_rctrl'               : 'Right CTRL',
	'KEY_lctrl'               : 'Left CTRL',
	'KEY_ralt'                : 'Right ALT',
	'KEY_lalt'                : 'Left ALT',
	'KEY_print'               : 'PrintScr',
	'KEY_scrolllock'          : 'SCROLL',
	'KEY_lwin'                : 'Left ⊞',
	'KEY_rwin'                : 'Right ⊞',
	'KEY_menu'                : '▤',
	'MOUSE_BUTTON_NONE'       : 'MOUSE NONE',
	'MOUSE_BUTTON_LEFT'       : 'MOUSE LEFT',
	'MOUSE_BUTTON_MIDDLE'     : 'MOUSE MIDDLE',
	'MOUSE_BUTTON_RIGHT'      : 'MOUSE RIGHT',
	'MOUSE_BUTTON_WHEEL_UP'   : 'MOUSE WHEEL UP',
	'MOUSE_BUTTON_WHEEL_DOWN' : 'MOUSE WHEEL DOWN',
	'MOUSE_BUTTON_X1'         : 'MOUSE BUTTON 4',
	'MOUSE_BUTTON_X2'         : 'MOUSE BUTTON 5',
	'AXIS_X'                  : 'AXIS_X',
	'AXIS_1'                  : 'AXIS_1',
	'AXIS_Y'                  : 'AXIS_Y',
	'AXIS_2'                  : 'AXIS_2',
	'AXIS_Z'                  : 'AXIS_Z',
	'AXIS_3'                  : 'AXIS_3',
	'AXIS_W'                  : 'AXIS_W',
	'AXIS_4'                  : 'AXIS_4',
	'AXIS_5'                  : 'AXIS_5',
	'AXIS_6'                  : 'AXIS_6',
	'AXIS_7'                  : 'AXIS_7',
	'AXIS_8'                  : 'AXIS_8',
	'AXIS_9'                  : 'AXIS_9',
	'AXIS_10'                 : 'AXIS_10',
	'AXIS_11'                 : 'AXIS_11',
	'AXIS_12'                 : 'AXIS_12',
	'AXIS_13'                 : 'AXIS_13',
	'AXIS_14'                 : 'AXIS_14',
}