function clientGetKeyMapSimple(keys, locale) {
	return keys.split(' ').map((key) => { return getKeyMap(key, locale)} ).join('+')
}
function clientGetKeyMap(keys, locale) {
	return keys.split('--')[1].split(' ').map((key) => { return getKeyMap(key, locale)}).join('+')
}
function getKeyMap(key, locale) {
	let thisKey = null

	thisKey ??= keyMap[key]
	thisKey ??= localKeys?.[locale]?.[key]
	thisKey ??= localKeys.en[key]

	return `<span class="btn disabled btn-sm btn-outline-secondary small">${thisKey}</span>`
}
const keyMap = {
	'AXIS_1'                  : '⤱ 1',
	'AXIS_2'                  : '⤱ 2',
	'AXIS_3'                  : '⤱ 3',
	'AXIS_4'                  : '⤱ 4',
	'AXIS_5'                  : '⤱ 5',
	'AXIS_6'                  : '⤱ 6',
	'AXIS_7'                  : '⤱ 7',
	'AXIS_8'                  : '⤱ 8',
	'AXIS_9'                  : '⤱ 9',
	'AXIS_10'                 : '⤱ 10',
	'AXIS_11'                 : '⤱ 11',
	'AXIS_12'                 : '⤱ 12',
	'AXIS_13'                 : '⤱ 13',
	'AXIS_14'                 : '⤱ 14',
	'AXIS_W'                  : '⤱ W',
	'AXIS_X'                  : '⤱ X',
	'AXIS_X+'                 : '⤱ X+',
	'AXIS_X-'                 : '⤱ X-',
	'AXIS_Y'                  : '⤱ Y',
	'AXIS_Y+'                 : '⤱ Y+',
	'AXIS_Y-'                 : '⤱ Y-',
	'AXIS_Z'                  : '⤱ Z',
	'KEY_0'                   : '0',
	'KEY_1'                   : '1',
	'KEY_2'                   : '2',
	'KEY_3'                   : '3',
	'KEY_4'                   : '4',
	'KEY_5'                   : '5',
	'KEY_6'                   : '6',
	'KEY_7'                   : '7',
	'KEY_8'                   : '8',
	'KEY_9'                   : '9',
	'KEY_a'                   : 'A',
	'KEY_ampersand'           : '&',
	'KEY_asterisk'            : '*',
	'KEY_at'                  : '@',
	'KEY_b'                   : 'B',
	'KEY_backquote'           : '`',
	'KEY_backslash'           : '\\',
	'KEY_backspace'           : '⌫',
	'KEY_c'                   : 'C',
	'KEY_caret'               : '~',
	'KEY_clear'               : 'CLR',
	'KEY_colon'               : ':',
	'KEY_comma'               : ',',
	'KEY_d'                   : 'D',
	'KEY_dollar'              : '$',
	'KEY_down'                : '↓',
	'KEY_e'                   : 'E',
	'KEY_equals'              : '=',
	'KEY_exclaim'             : '!',
	'KEY_f'                   : 'F',
	'KEY_f1'                  : 'F1',
	'KEY_f2'                  : 'F2',
	'KEY_f3'                  : 'F3',
	'KEY_f4'                  : 'F4',
	'KEY_f5'                  : 'F5',
	'KEY_f6'                  : 'F6',
	'KEY_f7'                  : 'F7',
	'KEY_f8'                  : 'F8',
	'KEY_f9'                  : 'F9',
	'KEY_f10'                 : 'F10',
	'KEY_f11'                 : 'F11',
	'KEY_f12'                 : 'F12',
	'KEY_f13'                 : 'F13',
	'KEY_f14'                 : 'F14',
	'KEY_f15'                 : 'F15',
	'KEY_g'                   : 'G',
	'KEY_greater'             : '>',
	'KEY_h'                   : 'H',
	'KEY_hash'                : '#',
	'KEY_i'                   : 'I',
	'KEY_j'                   : 'J',
	'KEY_k'                   : 'K',
	'KEY_KP_0'                : 'KEYPAD 0',
	'KEY_KP_1'                : 'KEYPAD 1',
	'KEY_KP_2'                : 'KEYPAD 2',
	'KEY_KP_3'                : 'KEYPAD 3',
	'KEY_KP_4'                : 'KEYPAD 4',
	'KEY_KP_5'                : 'KEYPAD 5',
	'KEY_KP_6'                : 'KEYPAD 6',
	'KEY_KP_7'                : 'KEYPAD 7',
	'KEY_KP_8'                : 'KEYPAD 8',
	'KEY_KP_9'                : 'KEYPAD 9',
	'KEY_KP_divide'           : 'KEYPAD /',
	'KEY_KP_enter'            : 'KEYPAD ⏎',
	'KEY_KP_equals'           : 'KEYPAD =',
	'KEY_KP_minus'            : 'KEYPAD -',
	'KEY_KP_multiply'         : 'KEYPAD *',
	'KEY_KP_period'           : 'KEYPAD .',
	'KEY_KP_plus'             : 'KEYPAD +',
	'KEY_l'                   : 'L',
	'KEY_left'                : '←',
	'KEY_leftbracket'         : '{',
	'KEY_leftparen'           : '[',
	'KEY_less'                : '<',
	'KEY_lwin'                : '⊞',
	'KEY_m'                   : 'M',
	'KEY_menu'                : '▤',
	'KEY_minus'               : '-',
	'KEY_n'                   : 'N',
	'KEY_o'                   : 'O',
	'KEY_p'                   : 'P',
	'KEY_period'              : '.',
	'KEY_plus'                : '+',
	'KEY_print'               : 'PrintScr',
	'KEY_q'                   : 'Q',
	'KEY_question'            : '?',
	'KEY_quote'               : '\'',
	'KEY_quotedbl'            : '"',
	'KEY_r'                   : 'R',
	'KEY_return'              : '⏎',
	'KEY_right'               : '→',
	'KEY_rightbracket'        : '}',
	'KEY_rightparen'          : ']',
	'KEY_rwin'                : '⊞',
	'KEY_s'                   : 'S',
	'KEY_scrolllock'          : 'SCROLL',
	'KEY_semicolon'           : ';',
	'KEY_slash'               : '/',
	'KEY_t'                   : 'T',
	'KEY_tab'                 : '⇥',
	'KEY_u'                   : 'U',
	'KEY_underscore'          : '_',
	'KEY_up'                  : '↑',
	'KEY_v'                   : 'V',
	'KEY_w'                   : 'W',
	'KEY_x'                   : 'X',
	'KEY_y'                   : 'Y',
	'KEY_z'                   : 'Z',
	'MOUSE_BUTTON_NONE'       : '🖯 NONE',
	'MOUSE_BUTTON_X1'         : '🖯 4',
	'MOUSE_BUTTON_X2'         : '🖯 5',
}

const localKeys = {
	'de' : {
		'KEY_delete'              : 'LÖSCHEN',
		'KEY_end'                 : 'ENDE',
		'KEY_esc'                 : 'ESC',
		'KEY_home'                : 'POS1',
		'KEY_insert'              : 'EINFÜGEN',
		'KEY_pagedown'            : 'BILD RUNTER',
		'KEY_pageup'              : 'BILD HOCH',
		'KEY_pause'               : 'PAUSE',
		'KEY_space'               : 'LEER',

		'KEY_lalt'                : 'ALT',
		'KEY_lctrl'               : 'STRG',
		'KEY_lshift'              : 'UMSCHALT LINKS',
		'KEY_ralt'                : 'ALT RECHTS',
		'KEY_rctrl'               : 'STRG RECHTS',
		'KEY_rshift'              : 'UMSCHALT RECHTS',

		'MOUSE_BUTTON_LEFT'       : '🖯 LINKS',
		'MOUSE_BUTTON_MIDDLE'     : '🖯 MITTE',
		'MOUSE_BUTTON_RIGHT'      : '🖯 RECHTS',
		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 MAUSRAD RUNTER',
		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 MAUSRAD HOCH',
	},
	'en' : {
		'KEY_delete'              : 'DELETE',
		'KEY_end'                 : 'END',
		'KEY_esc'                 : 'ESC',
		'KEY_home'                : 'HOME',
		'KEY_insert'              : 'INSERT',
		'KEY_pagedown'            : 'PAGE DOWN',
		'KEY_pageup'              : 'PAGE UP',
		'KEY_pause'               : 'PAUSE',
		'KEY_space'               : 'SPACE',

		'KEY_lalt'                : 'ALT',
		'KEY_lctrl'               : 'CTRL',
		'KEY_lshift'              : 'LEFT SHIFT',
		'KEY_ralt'                : 'RIGHT ALT',
		'KEY_rctrl'               : 'RIGHT CTRL',
		'KEY_rshift'              : 'RIGHT SHIFT',

		'MOUSE_BUTTON_LEFT'       : '🖯 LEFT',
		'MOUSE_BUTTON_MIDDLE'     : '🖯 MIDDLE',
		'MOUSE_BUTTON_RIGHT'      : '🖯 RIGHT',
		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 WHEEL DOWN',
		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 WHEEL UP',
	},
	'es' : {
		'KEY_delete'              : 'SUPR',
		'KEY_end'                 : 'FIN',
		'KEY_esc'                 : 'ASCEND',
		'KEY_home'                : 'INICIO',
		'KEY_insert'              : 'INSERTAR',
		'KEY_pagedown'            : 'AV PÁG',
		'KEY_pageup'              : 'RE PÁG',
		'KEY_pause'               : 'PAUSA',
		'KEY_space'               : 'ESPACIO',

		'KEY_lalt'                : 'ALT',
		'KEY_lctrl'               : 'CTRL',
		'KEY_lshift'              : 'MAYÚS IZQ',
		'KEY_ralt'                : 'ALT DERr',
		'KEY_rctrl'               : 'CTRL DER',
		'KEY_rshift'              : 'MAYÚS DER',

		'MOUSE_BUTTON_LEFT'       : '🖯 IZQUIERDA',
		'MOUSE_BUTTON_MIDDLE'     : '🖯 CENTRO',
		'MOUSE_BUTTON_RIGHT'      : '🖯 DERECHA',
		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 RUEDA ABAJO',
		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 RUEDA ARRIBA',
	},
	'fr' : {
		'KEY_delete'              : 'SUPPR',
		'KEY_end'                 : 'FIN',
		'KEY_esc'                 : 'ÉCHAP',
		'KEY_home'                : 'DÉBUT',
		'KEY_insert'              : 'INSER',
		'KEY_pagedown'            : 'PG SUIV',
		'KEY_pageup'              : 'PG PRÉC',
		'KEY_pause'               : 'PAUSE',
		'KEY_space'               : 'ESPACE',

		'KEY_lalt'                : 'ALT',
		'KEY_lctrl'               : 'CTRL',
		'KEY_lshift'              : 'MAJ GAUCHE',
		'KEY_ralt'                : 'ALT DROITE',
		'KEY_rctrl'               : 'CTRL DROITE',
		'KEY_rshift'              : 'MAJ DROITE',

		'MOUSE_BUTTON_LEFT'       : '🖯 GAUCHE',
		'MOUSE_BUTTON_MIDDLE'     : '🖯 MILIEU',
		'MOUSE_BUTTON_RIGHT'      : '🖯 DROITE',
		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 MOLETTE HAUT',
		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 MOLETTE BAS',
	},
	'nl' : {
		'KEY_delete'              : 'DELETE',
		'KEY_end'                 : 'END',
		'KEY_esc'                 : 'ESC',
		'KEY_home'                : 'HOME',
		'KEY_insert'              : 'INSERT',
		'KEY_pagedown'            : 'PAGE DOWN',
		'KEY_pageup'              : 'PAGE UP',
		'KEY_pause'               : 'PAUSE',
		'KEY_space'               : 'SPATIEBALK',

		'KEY_lalt'                : 'ALT',
		'KEY_lctrl'               : 'CTRL',
		'KEY_lshift'              : 'LINKER SHIFT',
		'KEY_ralt'                : 'RECHTER ALT',
		'KEY_rctrl'               : 'RECHTER CTRL',
		'KEY_rshift'              : 'RECHTER SHIFT',

		'MOUSE_BUTTON_LEFT'       : '🖯 LINKS',
		'MOUSE_BUTTON_MIDDLE'     : '🖯 MIDDEN',
		'MOUSE_BUTTON_RIGHT'      : '🖯 RECHTS',
		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 SCROLL OMLAAG',
		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 SCROLL OMHOOG',
	},
	'ru' : {
		'KEY_delete'              : 'DELETE',
		'KEY_end'                 : 'END',
		'KEY_esc'                 : 'ESC',
		'KEY_home'                : 'HOME',
		'KEY_insert'              : 'INSERT',
		'KEY_pagedown'            : 'PAGE DOWN',
		'KEY_pageup'              : 'PAGE UP',
		'KEY_pause'               : 'PAUSE',
		'KEY_space'               : 'ПРОБЕЛ',

		'KEY_lalt'                : 'ALT',
		'KEY_lctrl'               : 'CTRL',
		'KEY_lshift'              : 'ЛЕВЫЙ SHIFT',
		'KEY_ralt'                : 'ПРАВЫЙ ALT',
		'KEY_rctrl'               : 'ПРАВЫЙ CTRL',
		'KEY_rshift'              : 'ПРАВЫЙ SHIFT',
		
		'MOUSE_BUTTON_LEFT'       : 'ЛЕВАЯ КЛАВИША МЫШИ',
		'MOUSE_BUTTON_MIDDLE'     : 'СРЕДНЯЯ КЛАВИША МЫШИ',
		'MOUSE_BUTTON_RIGHT'      : 'ПРАВАЯ КЛАВИША МЫШИ',
		'MOUSE_BUTTON_WHEEL_DOWN' : 'КОЛЁСИКО МЫШИ ВНИЗ',
		'MOUSE_BUTTON_WHEEL_UP'   : 'КОЛЁСИКО МЫШИ ВВЕРХ',
	},
}